version: latest

services:
  # mongodb:
  #   image: mongo:latest
  #   container_name: test-mongodb
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: admin
  #     MONGO_INITDB_DATABASE: database
  #   volumes:
  #     - mongodb_data:/data/db
  db:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    volumes:
      - postgres-data:/var/lib/postgresql/data
  discord:
    build:
      dockerfile: Bot.Dockerfile
      args:
        BUILD_PLATFORM: "linux/arm64"
    environment:
      TOKEN:
      CLIENT_ID: 1434329527152017458
      GUILD_ID: 1300648645372285029
      API_URL: http://api:3000/
    container_name: discord_bot
    restart: unless-stopped
    depends_on:
      - db
  api:
    build:
      dockerfile: Api.Dockerfile
      args:
        BUILD_PLATFORM: "linux/arm64"
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres_db:5432/database
    container_name: api
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  postgres-data: