version: latest

services:
  # mongodb:
  #   image: mongo:latest
  #   container_name: test-mongodb
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: admin
  #     MONGO_INITDB_DATABASE: database
  #   volumes:
  #     - mongodb_data:/data/db
  db:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    volumes:
      - postgres-data:/var/lib/postgresql/data
  discord:
    image: bugg86/usav3-bot:latest
    container_name: discord_bot
    restart: unless-stopped
  api:
    image: bugg86/usav3-botapi:latest
    container_name: api
    restart: unless-stopped
    ports:
      - '3000:3000'

volumes:
  postgres-data: